version: 0.2

env:
    variables:
        GOOGLE_APPLICATION_CREDENTIALS: "gcp-key.json"

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build
    post_build:
        commands:
            - npm run aws-set-gcp-key
            - npm run test-2

cache:
    paths:
        - "node_modules/**/*"
