# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
    node10:
        docker:
            - image: circleci/node:10
        working_directory: ~/repo
    node8:
        docker:
            - image: circleci/node:8
        working_directory: ~/repo

jobs:
    build_and_test:
        description: "build faast.js"
        parameters:
            nodeVersion:
                type: string
            executor:
                type: executor
        executor: << parameters.executor >>
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - <<parameters.nodeVersion>>-{{ checksum "package.json" }}
                      - <<parameters.nodeVersion>>
            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: <<parameters.nodeVersion>>-{{ checksum "package.json" }}
            - run: npm run build
            - run: npm run set-gcp-key
            - run: npx nyc npm run test
            - run:
                  command: npm run codecov
                  when: always

workflows:
    version: 2
    node10:
        jobs:
            - build_and_test:
                  nodeVersion: "node10"
                  executor: node10
    node8:
        jobs:
            - build_and_test:
                  requires:
                      - node10
                  nodeVersion: "node8"
                  executor: node8
