# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        docker:
            - image: circleci/node:10
        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

            - run: npm run build
    test-local:
        docker:
            - image: circleci/node:10
        steps:
            - run: npm run test-local
    test-aws:
        docker:
            - image: circleci/node:10
        steps:
            - run: npm run test-aws-remote
    test-google:
        docker:
            - image: circleci/node:10
        steps:
            - run: npm run set-gcp-key
            - run: npm run test-google-remote
workflows:
    version: 2
    build_and_test: build
        jobs:
            - build
            - test-local:
                requires:
                    - build
            - test-aws:
                requires:
                    - test-local
            - test-google:
                requires:
                    - test-local
