# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

executors:
    node10:
        docker:
            - image: circleci/node:10
        working_directory: ~/repo

jobs:
    build:
        executor: node10
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run: npm install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run: npm run build
            - persist_to_workspace:
                  root: .
                  paths:
                      - .

    test-local:
        executor: node10
        steps:
            - attach_workspace:
                  at: ~/repo
            - run: npx nyc npm run test-local
            - run:
                  command: npm run codecov
                  when: always

    test-aws:
        executor: node10
        steps:
            - attach_workspace:
                  at: ~/repo
            - run: npx nyc npm run test-aws-remote
            - run:
                  command: npm run codecov
                  when: always

    test-google:
        executor: node10
        steps:
            - attach_workspace:
                  at: ~/repo
            - run: npm run set-gcp-key
            - run: npx nyc npm run test-google-remote
            - run:
                  command: npm run codecov
                  when: always

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test-local:
                  requires:
                      - build
            - test-aws:
                  requires:
                      - test-local
            - test-google:
                  requires:
                      - test-aws
